name: Deploy Spring boot to Amazon EC2

on:
  push:
    branches:
      - main
      
permissions:
  contents: read

env:
  PROJECT_NAME: action_codedeploy

jobs:
  build:
    name: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build With Gradle
        run: |
          ./gradlew clean build --stacktrace
      
      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://aws-community-demo-build/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy to Auto Scaling Group
        run: aws deploy create-deployment --application-name demo-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name scaled --s3-location bucket=aws-community-demo-build,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
